# Generated by Django 4.0.2 on 2022-04-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_category_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
