# Generated by Django 4.0.2 on 2022-04-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_user_watchlist_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='categorychoice',
            field=models.CharField(choices=[(1, 'Shoes'), (2, 'Clothes'), (3, 'Homeware'), (4, 'Car'), (5, 'Baby'), (6, 'Toys'), (7, 'Electronics')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(to='auctions.Category'),
        ),
    ]
