# Generated by Django 4.0.2 on 2022-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_category_category_category_categorychoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorychoice',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Homeware', 'Homeware'), ('Car', 'Car'), ('Baby', 'Baby'), ('Toys', 'Toys'), ('Electronics', 'Electronics')], default=1, max_length=12),
        ),
    ]
