# Generated by Django 4.0.2 on 2022-04-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_category_categorychoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categorychoice',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Homeware', 'Homeware'), ('Car', 'Car'), ('Baby', 'Baby'), ('Toys', 'Toys'), ('Electronics', 'Electronics')], default='Shoes', max_length=12),
        ),
    ]
