# Generated by Django 4.0.2 on 2022-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_category_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Homeware', 'Homeware'), ('Car', 'Car'), ('Baby', 'Baby'), ('Toys', 'Toys'), ('Electronics', 'Electronics')], max_length=12),
        ),
    ]
