# Generated by Django 4.0.2 on 2022-04-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('expire', models.DateTimeField(null=True)),
                ('bids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listbid', to='auctions.bid')),
                ('listauction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listauction', to='auctions.listing')),
            ],
        ),
    ]
