# Generated by Django 4.0.2 on 2022-04-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='expire',
        ),
        migrations.AlterField(
            model_name='auction',
            name='listauction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
