# Generated by Django 4.0.2 on 2022-04-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auction_expire_alter_auction_listauction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
