# Generated by Django 4.0.2 on 2022-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auction_bids_alter_bid_date_alter_bid_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bids',
            new_name='bid',
        ),
    ]
