# Generated by Django 4.0.2 on 2022-04-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_auction_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
    ]
