# Generated by Django 4.0.2 on 2022-04-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_comment_date_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
